<<<<<<< HEAD
import { Geist, Geist_Mono, Space_Mono } from "next/font/google";
=======
import { Geist, Geist_Mono } from "next/font/google";
>>>>>>> f5be4475a8e908b3015631d9ba44ab922fe43623
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
const spaceRegular = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "AstroDex",
  description: "Created by Sk Zubair Ahmed.",
=======
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> f5be4475a8e908b3015631d9ba44ab922fe43623
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
<<<<<<< HEAD
      className={`${geistSans.variable} ${geistMono.variable} ${spaceRegular.variable} h-full antialiased`}
=======
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
>>>>>>> f5be4475a8e908b3015631d9ba44ab922fe43623
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
<<<<<<< HEAD
}q
=======
}
>>>>>>> f5be4475a8e908b3015631d9ba44ab922fe43623
